package MyNumbersModule;


/**
* MyNumbersModule/LongSequenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Numbers.idl
* 23 окт€бр€ 2023 г. 22:55:03 MSK
*/

public final class LongSequenceHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public LongSequenceHolder ()
  {
  }

  public LongSequenceHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyNumbersModule.LongSequenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyNumbersModule.LongSequenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyNumbersModule.LongSequenceHelper.type ();
  }

}
