package MyNumbersModule;


/**
* MyNumbersModule/MyNumbers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Numbers.idl
* 23 окт€бр€ 2023 г. 22:55:03 MSK
*/

public interface MyNumbers extends MyNumbersOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MyNumbers
