package MyNumbersModule;


/**
* MyNumbersModule/MyNumbersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Numbers.idl
* 23 окт€бр€ 2023 г. 22:55:03 MSK
*/

abstract public class MyNumbersHelper
{
  private static String  _id = "IDL:MyNumbersModule/MyNumbers:1.0";

  public static void insert (org.omg.CORBA.Any a, MyNumbersModule.MyNumbers that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MyNumbersModule.MyNumbers extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MyNumbersModule.MyNumbersHelper.id (), "MyNumbers");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MyNumbersModule.MyNumbers read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MyNumbersStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MyNumbersModule.MyNumbers value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MyNumbersModule.MyNumbers narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MyNumbersModule.MyNumbers)
      return (MyNumbersModule.MyNumbers)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MyNumbersModule._MyNumbersStub stub = new MyNumbersModule._MyNumbersStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MyNumbersModule.MyNumbers unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MyNumbersModule.MyNumbers)
      return (MyNumbersModule.MyNumbers)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MyNumbersModule._MyNumbersStub stub = new MyNumbersModule._MyNumbersStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
