package MyNumbersModule;


/**
* MyNumbersModule/MyNumbersOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Numbers.idl
* 23 окт€бр€ 2023 г. 22:55:03 MSK
*/

public interface MyNumbersOperations 
{
  int[] getNegativeNumbers ();
  void addRandomNumbers (int number);
  int[] getNumberSet ();
} // interface MyNumbersOperations
